#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
cot_protocol.py - Cursor-on-Target (CoT) Protocol Implementation

Implements CoT XML parsing and generation for ATAK/WINTAK compatibility.
Supports standard CoT event types and bidirectional conversion.
"""

import xml.etree.ElementTree as ET
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional, Any
import uuid
import logging

logger = logging.getLogger("lpu5-cot")


class CoTEvent:
    """Represents a Cursor-on-Target event"""
    
    # CoT Type Classifications
    ATOM_TYPES = {
        "friendly": "a-f",
        "hostile": "a-h",
        "neutral": "a-n",
        "unknown": "a-u",
        "pending": "a-p"
    }
    
    ENTITY_TYPES = {
        "ground_unit": "G",
        "aircraft": "A",
        "space": "P",
        "surface": "S",
        "subsurface": "U"
    }
    
    def __init__(self,
                 uid: str,
                 cot_type: str,
                 lat: float,
                 lon: float,
                 hae: float = 0.0,
                 ce: float = 9999999.0,
                 le: float = 9999999.0,
                 callsign: Optional[str] = None,
                 remarks: Optional[str] = None,
                 team_name: Optional[str] = None,
                 team_role: Optional[str] = None,
                 stale_minutes: int = 5,
                 how: str = "m-g",
                 color: Optional[int] = None,
                 has_meshtastic_detail: bool = False,
                 contact_endpoint: Optional[str] = None,
                 is_meshtastic_node: bool = False,
                 meshtastic_short_name: Optional[str] = None):
        """
        Initialize a CoT event
        
        Args:
            uid: Unique identifier for the entity
            cot_type: CoT type string (e.g., "a-f-G-U-C" for friendly ground unit)
            lat: Latitude in decimal degrees
            lon: Longitude in decimal degrees
            hae: Height above ellipsoid in meters
            ce: Circular error in meters
            le: Linear error in meters
            callsign: Entity callsign/name
            remarks: Additional remarks
            team_name: Team name
            team_role: Role within team
            stale_minutes: Minutes until event is stale
            how: How the event was generated (e.g. "m-g" machine-generated,
                 "h-g-i-g-o" human-placed, "h-e" human-entered coordinates)
            color: ATAK signed ARGB integer color value for spot-map markers
            has_meshtastic_detail: True when the raw CoT XML detail contained a
                <meshtastic> child element (set by from_xml(); indicates the
                event was forwarded by an ATAK Meshtastic plugin).
            contact_endpoint: Optional TAK endpoint string (``<host>:<port>:tcp``)
                added to the ``<contact>`` element so ATAK displays the entity as a
                reachable Contact and allows operators to send CoT data directly to it.
            is_meshtastic_node: True when this CoT event represents a Meshtastic
                node generated by LPU5 (set by marker_to_cot() for node/meshtastic_node/
                gateway types).  Used to suppress ``<archive/>`` so that ATAK treats
                these as live refreshing contacts rather than static map markers.
            meshtastic_short_name: Short display name extracted from the
                ``<meshtastic shortName="...">`` element in the CoT XML detail.
                Used by cot_to_marker() to populate the ``shortName`` field
                (max 4 chars) in the marker API response.
        """
        self.uid = uid
        self.cot_type = cot_type
        self.lat = lat
        self.lon = lon
        self.hae = hae
        self.ce = ce
        self.le = le
        self.callsign = callsign or uid
        self.remarks = remarks
        self.team_name = team_name
        self.team_role = team_role
        self.time = datetime.now(timezone.utc)
        self.start = self.time
        self.stale = self.time + timedelta(minutes=stale_minutes)
        self.how = how
        self.color = color
        self.has_meshtastic_detail = has_meshtastic_detail
        self.contact_endpoint = contact_endpoint
        self.is_meshtastic_node = is_meshtastic_node
        self.meshtastic_short_name = meshtastic_short_name
        
    @staticmethod
    def build_cot_type(atom: str = "friendly",
                       entity: str = "ground_unit",
                       function: str = "U",  # Unit
                       detail: str = "C") -> str:  # Combat
        """
        Build a CoT type string from components
        
        Args:
            atom: Affiliation (friendly, hostile, neutral, unknown, pending)
            entity: Entity type (ground_unit, aircraft, surface, subsurface, space)
            function: Function code (default: U for Unit)
            detail: Detail code (default: C for Combat)
            
        Returns:
            Complete CoT type string (e.g., "a-f-G-U-C")
        """
        atom_code = CoTEvent.ATOM_TYPES.get(atom, "a-u")
        entity_code = CoTEvent.ENTITY_TYPES.get(entity, "G")
        return f"{atom_code}-{entity_code}-{function}-{detail}"
    
    def to_xml(self) -> str:
        """
        Convert this CoT event to XML string
        
        Returns:
            XML string representation of the CoT event
        """
        # Root event element
        event = ET.Element("event")
        event.set("version", "2.0")
        event.set("uid", self.uid)
        event.set("type", self.cot_type)
        event.set("how", self.how)
        event.set("time", self._format_time(self.time))
        event.set("start", self._format_time(self.start))
        event.set("stale", self._format_time(self.stale))
        
        # Point element with coordinates
        point = ET.SubElement(event, "point")
        point.set("lat", str(self.lat))
        point.set("lon", str(self.lon))
        point.set("hae", str(self.hae))
        point.set("ce", str(self.ce))
        point.set("le", str(self.le))
        
        # Detail element with additional info
        detail = ET.SubElement(event, "detail")
        
        # Contact information
        if self.callsign:
            contact = ET.SubElement(detail, "contact")
            contact.set("callsign", self.callsign)
            # Include the endpoint so ATAK displays this entity as a reachable
            # Contact (not just a passive map marker) and allows operators to
            # send CoT events directly to it.
            if self.contact_endpoint:
                contact.set("endpoint", self.contact_endpoint)

        # WinTAK/ATAK requires a <uid Droid="callsign"> element in the detail
        # section of PLI events so that the unit name is displayed correctly on
        # the map and the entity is treated as an active Position Location
        # Information contact rather than a static point marker.
        # Placement immediately after <contact> matches the order used by ATAK
        # when it generates native PLI events (contact → uid → __group → …).
        if self.is_meshtastic_node and self.callsign:
            uid_elem = ET.SubElement(detail, "uid")
            uid_elem.set("Droid", self.callsign)
        
        # Group/team information – every Meshtastic node needs a <__group>
        # element so that WinTAK/ATAK displays it as an individual SA contact
        # in the contacts list rather than as a static map marker.  Fall back
        # to "Cyan" / "Team Member" when no explicit team is configured, which
        # mirrors the values used by the LPU5-GW SA beacon.
        _grp_name = self.team_name or ("Cyan" if self.is_meshtastic_node else None)
        _grp_role = self.team_role or ("Team Member" if self.is_meshtastic_node else None)
        if _grp_name or _grp_role:
            group = ET.SubElement(detail, "__group")
            if _grp_name:
                group.set("name", _grp_name)
            if _grp_role:
                group.set("role", _grp_role)
        
        # Add a <meshtastic> element so that ATAK / WinTAK knows this CoT event
        # originated from a Meshtastic node or GPS position.  Emitted for all
        # is_meshtastic_node events (node, meshtastic_node, gateway, gps_position)
        # regardless of CoT type, so that ATAK handles them as live SA contacts.
        if self.is_meshtastic_node and self.callsign:
            mesh_elem = ET.SubElement(detail, "meshtastic")
            mesh_elem.set("longName", self.callsign)
            short = (self.meshtastic_short_name or self.callsign[:4])[:4]
            mesh_elem.set("shortName", short)

        # Remarks
        if self.remarks:
            remarks_elem = ET.SubElement(detail, "remarks")
            remarks_elem.text = self.remarks

        # Spot-map and drawing markers need <archive/> so ATAK persists them on
        # the map after they go stale.  Without this element ATAK removes the
        # entity from its overlay once the stale timestamp is reached.
        # Military-affiliation markers (a-f/h/n/u) placed by LPU5 users are
        # also archived so they persist on the ATAK map like spot-map markers.
        #
        # Meshtastic nodes (type "node"/"meshtastic_node"/"gateway") and GPS
        # positions are live SA contacts refreshed periodically.  They must NOT
        # receive <archive/> so ATAK displays them as refreshing contacts rather
        # than static markers.  The is_meshtastic_node flag is the authoritative
        # signal regardless of the CoT type used (a-f-G-U-C or a-f-G-E-S-U-M).
        if (self.cot_type.startswith(("b-m", "u-d", "a-f", "a-h", "a-n", "a-u", "a-p"))
                and not self.is_meshtastic_node):
            ET.SubElement(detail, "archive")

        # Emit ATAK color element for spot-map markers so that the correct
        # color is rendered in ATAK/WinTAK.  The value is a signed ARGB int.
        if self.cot_type.startswith("b-m-p-s-m") and self.color is not None:
            color_elem = ET.SubElement(detail, "color")
            color_elem.set("argb", str(self.color))

        # Track information (for movement history)
        track = ET.SubElement(detail, "track")
        track.set("speed", "0.0")
        track.set("course", "0.0")
        
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' + ET.tostring(event, encoding="unicode")
    
    @staticmethod
    def from_xml(xml_string: str) -> Optional['CoTEvent']:
        """
        Parse a CoT XML string into a CoTEvent object
        
        Args:
            xml_string: XML string to parse
            
        Returns:
            CoTEvent object or None if parsing fails
        """
        try:
            root = ET.fromstring(xml_string)
            
            # Extract required attributes
            uid = root.get("uid")
            cot_type = root.get("type")
            how = root.get("how", "m-g")
            
            # Extract point coordinates
            point = root.find("point")
            if point is None:
                logger.warning("CoT event missing point element")
                return None
                
            lat = float(point.get("lat", "0.0"))
            lon = float(point.get("lon", "0.0"))
            hae = float(point.get("hae", "0.0"))
            ce = float(point.get("ce", "9999999.0"))
            le = float(point.get("le", "9999999.0"))
            
            # Extract detail information
            detail = root.find("detail")
            callsign = None
            remarks = None
            team_name = None
            team_role = None
            
            if detail is not None:
                contact = detail.find("contact")
                if contact is not None:
                    callsign = contact.get("callsign")
                
                group = detail.find("__group")
                if group is not None:
                    team_name = group.get("name")
                    team_role = group.get("role")
                
                remarks_elem = detail.find("remarks")
                if remarks_elem is not None:
                    remarks = remarks_elem.text
            
            # Detect whether the CoT detail contains a <meshtastic> element,
            # which is added by ATAK Meshtastic plugins (e.g. atak-forwarder)
            # to identify Meshtastic node position events.
            has_meshtastic_detail = CoTProtocolHandler.detail_has_meshtastic(detail)

            # Extract the shortName from <meshtastic shortName="..."> when present.
            meshtastic_short_name = None
            if has_meshtastic_detail and detail is not None:
                mesh_el = detail.find("meshtastic")
                if mesh_el is not None:
                    meshtastic_short_name = mesh_el.get("shortName") or None

            # Calculate stale time (default 5 minutes from now)
            stale_str = root.get("stale")
            stale_minutes = 5
            if stale_str:
                try:
                    stale_time = datetime.strptime(stale_str, "%Y-%m-%dT%H:%M:%S.%fZ")
                    now = datetime.now(timezone.utc)
                    stale_delta = stale_time - now
                    stale_minutes = max(1, int(stale_delta.total_seconds() / 60))
                except Exception:
                    pass
            
            return CoTEvent(
                uid=uid,
                cot_type=cot_type,
                lat=lat,
                lon=lon,
                hae=hae,
                ce=ce,
                le=le,
                callsign=callsign,
                remarks=remarks,
                team_name=team_name,
                team_role=team_role,
                stale_minutes=stale_minutes,
                how=how,
                has_meshtastic_detail=has_meshtastic_detail,
                meshtastic_short_name=meshtastic_short_name,
            )
            
        except Exception as e:
            logger.error(f"Failed to parse CoT XML: {e}")
            return None
    
    @staticmethod
    def _format_time(dt: datetime) -> str:
        """Format datetime for CoT XML"""
        return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return {
            "uid": self.uid,
            "type": self.cot_type,
            "lat": self.lat,
            "lon": self.lon,
            "hae": self.hae,
            "ce": self.ce,
            "le": self.le,
            "callsign": self.callsign,
            "remarks": self.remarks,
            "team_name": self.team_name,
            "team_role": self.team_role,
            "time": self._format_time(self.time),
            "start": self._format_time(self.start),
            "stale": self._format_time(self.stale),
            "how": self.how
        }


class CoTProtocolHandler:
    """Handles CoT protocol operations including conversion and validation"""

    # Mapping from LPU5 symbol type names to TAK-compatible CoT type codes.
    # These must match the identifiers used by ATAK/ITAK/WinTAK/XTAK exactly
    # so that symbols sync correctly across all TAK server implementations.
    #
    # LPU5 shapes are mapped to ATAK military-affiliation CoT types that share
    # Meshtastic node types all use the a-f-G-E-S-U-M CoT type (Meshtastic
    # equipment) so that ATAK displays each node with the dedicated Meshtastic
    # icon as an individually identifiable device.  Previously person nodes
    # used a-f-G-U-P (PLI/Personnel) and gateway nodes used a-f-G-U-C
    # (Combat), which caused ATAK to cluster them with standard unit markers
    # instead of showing them as distinct Meshtastic contacts.
    LPU5_TO_COT_TYPE: Dict[str, str] = {
        "hostile":          "a-h-G-U-C",   # hostile ground unit (red diamond)
        "neutral":          "a-n-G-U-C",   # neutral ground unit (green square)
        "unknown":          "a-u-G-U-C",   # unknown ground unit (yellow flower)
        "friendly":         "a-f-G-U-C",   # friendly ground unit (blue rectangle)
        "pending":          "a-p-G-U-C",   # pending ground unit
        "gps_position":     "a-f-G-E-S-U-M",   # live GPS position (Meshtastic equipment in ATAK)
        "node":             "a-f-G-E-S-U-M",   # Meshtastic equipment node
        "meshtastic_node":  "a-f-G-E-S-U-M",   # Meshtastic node (blue M-circle in ATAK)
        "gateway":          "a-f-G-E-S-U-M",   # Meshtastic gateway/router (equipment)
        "tak_maker":        "a-f-G-U-C",   # ATAK SA / GPS position marker
        # CBT variants: ATAK-sourced markers rendered with "CBT" label to
        # distinguish them from natively created LPU5 markers.
        "cbt_hostile":      "a-h-G-U-C",   # ATAK hostile (red diamond + CBT)
        "cbt_friendly":     "a-f-G-U-C",        # ATAK friendly (blue rectangle + CBT)
        "cbt_neutral":      "a-n-G-U-C",   # ATAK neutral (green square + CBT)
        "cbt_unknown":      "a-u-G-U-C",   # ATAK unknown (yellow flower + CBT)
    }

    # Remaps the four basic LPU5 shape types to their ATAK-sourced CBT variants.
    # Applied to every marker that arrives via CoT so that ATAK-originated data
    # is immediately distinguishable from natively created LPU5 markers.
    ATAK_TO_CBT_TYPE: Dict[str, str] = {
        "hostile":  "cbt_hostile",
        "friendly": "cbt_friendly",
        "neutral":  "cbt_neutral",
        "unknown":  "cbt_unknown",
    }

    # Mapping from normalized lowercase hex color strings to ATAK team names.
    # ATAK uses team colors to visually group units on the situational-awareness
    # map.  Only the four most common LPU5 marker colors are mapped here;
    # unknown colors fall through to None (no team override).
    HEX_COLOR_TO_TEAM: Dict[str, str] = {
        "#ffff00": "Yellow",
        "#0000ff": "Blue",
        "#00ff00": "Green",
        "#ff0000": "Red",
    }

    # LPU5 type → web path for the corresponding SVG icon in /assets/symbols/.
    # Used by get_symbol_link() and the marker API to expose a ``symbolLink``
    # field without embedding SVG HTML in the JSON response.
    SYMBOL_LINK_MAP: Dict[str, str] = {
        "meshtastic_node": "/assets/symbols/meshtastic_node.svg",
        "node":            "/assets/symbols/meshtastic_node.svg",
        "gateway":         "/assets/symbols/meshtastic_node.svg",
        "gps_position":    "/assets/symbols/meshtastic_node.svg",
        "cbt_hostile":     "/assets/symbols/cbt_hostile.svg",
        "cbt_friendly":    "/assets/symbols/cbt_friendly.svg",
        "cbt_neutral":     "/assets/symbols/cbt_neutral.svg",
        "cbt_unknown":     "/assets/symbols/cbt_unknown.svg",
        "tak_maker":       "/assets/symbols/tak_maker.svg",
    }

    # Reverse mapping: TAK CoT type prefix → LPU5 symbol type.
    # Stored as a list of (prefix, lpu5_type) tuples ordered longest-prefix
    # first so that more-specific codes are matched before shorter ones when
    # iterating with str.startswith().
    #
    # ATAK military-affiliation types map to the LPU5 shape that shares the
    # same colour convention:
    #   a-f (Friendly, blue)   → friendly (blue rectangle)
    #   a-u (Unknown, yellow)  → unknown  (yellow flower)
    #   a-n (Neutral, green)   → neutral  (green square)
    #   a-h (Hostile, red)     → hostile  (red diamond)
    COT_TO_LPU5_TYPE: List[tuple] = [
        ("b-m-p-s-m", "hostile"),   # TAK spot-map marker (all shapes)
        ("u-d-c-e",   "hostile"),   # TAK drawing ellipse → diamond
        ("u-d-c-c",   "hostile"),   # TAK drawing circle → diamond
        ("u-d-r",     "friendly"),  # TAK drawing rectangle
        ("u-d-f",     "hostile"),   # TAK drawing freehand → diamond
        ("u-d-p",     "hostile"),   # TAK drawing generic point → diamond
        ("a-f-G-E-S-U-M", "meshtastic_node"),  # Meshtastic equipment → meshtastic_node
        ("a-f-G-E",   "meshtastic_node"),  # Friendly ground equipment (Meshtastic nodes via ATAK plugin)
        ("a-f",       "friendly"),  # friendly affiliation → blue rectangle
        ("a-h",       "hostile"),   # hostile affiliation → red diamond
        ("a-n",       "neutral"),   # neutral affiliation → green square
        ("a-u",       "unknown"),   # unknown affiliation → yellow flower
        ("a-p",       "hostile"),   # pending affiliation → red diamond
    ]

    @classmethod
    def lpu5_type_to_cot(cls, lpu5_type: str) -> str:
        """
        Convert a lowercase LPU5 symbol type to a TAK CoT type string.
        Falls back to the generic unknown ground-unit code if not found.
        """
        return cls.LPU5_TO_COT_TYPE.get(lpu5_type.lower(), "a-u-G-U-C")

    @classmethod
    def cot_type_to_lpu5(cls, cot_type: str) -> str:
        """
        Convert a TAK CoT type string to the corresponding LPU5 symbol type.
        Uses prefix matching (longest-first order) so sub-types resolve to
        their base category.  Falls back to "unknown".
        """
        for prefix, lpu5 in cls.COT_TO_LPU5_TYPE:
            if cot_type.startswith(prefix):
                return lpu5
        return "unknown"

    @staticmethod
    def detail_has_meshtastic(detail_elem: Optional[ET.Element]) -> bool:
        """
        Return True if the CoT ``<detail>`` element contains a ``<meshtastic>``
        child element.

        ATAK Meshtastic plugins (e.g. atak-forwarder) add this element to CoT
        events that originate from a Meshtastic node, making it the canonical
        way to distinguish Meshtastic-relayed positions from regular ATAK SA.

        Args:
            detail_elem: An ``xml.etree.ElementTree.Element`` for the
                         ``<detail>`` node, or ``None``.

        Returns:
            True if a ``<meshtastic>`` child is present, False otherwise.
        """
        return detail_elem is not None and detail_elem.find("meshtastic") is not None

    @staticmethod
    def get_symbol_link(lpu5_type: str) -> Optional[str]:
        """
        Return the web path to the SVG symbol asset for the given LPU5 type.

        Used by the marker API to provide a ``symbolLink`` field so the frontend
        can load the correct icon directly from the server without embedding SVG
        HTML in the JSON response.

        Args:
            lpu5_type: LPU5 internal marker type string (e.g. 'meshtastic_node',
                       'cbt_hostile', 'tak_maker', ...).

        Returns:
            Path string such as ``'/assets/symbols/meshtastic_node.svg'``,
            or ``None`` for types that have no dedicated SVG asset.
        """
        return CoTProtocolHandler.SYMBOL_LINK_MAP.get(lpu5_type)

    @staticmethod
    def hex_to_argb_int(hex_color: str) -> Optional[int]:
        """
        Convert an HTML hex color string to an ATAK signed 32-bit ARGB integer.

        ATAK encodes colors as signed 32-bit integers in ARGB byte order
        (alpha in the most-significant byte).  Full opacity (alpha=0xFF) is
        assumed when the input is a 6-digit ``#RRGGBB`` string.  8-digit
        ``#AARRGGBB`` strings are also supported.

        Args:
            hex_color: Color string in ``#RRGGBB`` or ``#AARRGGBB`` format.

        Returns:
            Signed 32-bit ARGB integer, or None if the input cannot be parsed.
        """
        try:
            h = hex_color.lstrip("#")
            if len(h) == 6:
                r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
                argb = (0xFF << 24) | (r << 16) | (g << 8) | b
            elif len(h) == 8:
                a, r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), int(h[6:8], 16)
                argb = (a << 24) | (r << 16) | (g << 8) | b
            else:
                return None
            # Reinterpret as signed 32-bit integer (ATAK expects a Java int)
            if argb >= 0x80000000:
                argb -= 0x100000000
            return argb
        except (ValueError, AttributeError):
            return None

    @classmethod
    def hex_color_to_team(cls, hex_color: str) -> Optional[str]:
        """
        Map a hex color string to an ATAK team name.

        Args:
            hex_color: Color string in ``#RRGGBB`` format.

        Returns:
            ATAK team name string, or None if the color is not mapped.
        """
        if not hex_color:
            return None
        return cls.HEX_COLOR_TO_TEAM.get(hex_color.lower())
    @staticmethod
    def marker_to_cot(marker: Dict[str, Any]) -> Optional[CoTEvent]:
        """
        Convert a map marker to CoT event

        Args:
            marker: Map marker dictionary

        Returns:
            CoTEvent object or None if conversion fails
        """
        try:
            uid = marker.get("id", str(uuid.uuid4()))
            lat = float(marker.get("lat", 0.0))
            lon = float(marker.get("lng", 0.0))

            # Determine the LPU5 internal type first so we can decide whether
            # to trust any stored cot_type value.
            lpu5_type = (marker.get("type") or marker.get("status") or "unknown").lower()

            # Meshtastic node/gateway markers always use the CoT type derived
            # from the marker's type field (a-f-G-E-S-U-M for nodes and gateway).
            # Any cot_type stored in marker.data from a previous ATAK echo is
            # ignored so that the node is always sent with the correct type.
            _MESHTASTIC_LPU5_TYPES = ("node", "meshtastic_node", "gateway", "gps_position")
            if lpu5_type in _MESHTASTIC_LPU5_TYPES:
                cot_type = CoTProtocolHandler.lpu5_type_to_cot(lpu5_type)
            else:
                # For non-Meshtastic markers, reuse a TAK-originated cot_type
                # so that the exact symbol (including sub-type detail) is
                # preserved when re-broadcasting to other TAK clients.
                cot_type = marker.get("cot_type") or marker.get("cotType")
                if not cot_type:
                    # Derive a TAK CoT type from the LPU5 symbol type field,
                    # falling back to the status field for backwards
                    # compatibility (matches the JS markerToCOT() logic).
                    cot_type = CoTProtocolHandler.lpu5_type_to_cot(lpu5_type)

            # Preserve the original `how` attribute when re-broadcasting a
            # TAK-originated marker so that ATAK clients receive the correct
            # provenance.  Fall back to "m-g" (machine-generated) so that
            # meshtastic-node events and server-generated pings are still
            # marked correctly.
            how = marker.get("how") or marker.get("cot_how") or "m-g"

            # Derive ATAK color value and team name from the marker's hex color.
            # Team name takes precedence if explicitly set on the marker; the
            # color field is used as a fallback so that spot-map markers
            # created in LPU5 appear with the correct color in ATAK.
            hex_color = marker.get("color")
            argb_color: Optional[int] = None
            team_name: Optional[str] = marker.get("team")
            if hex_color:
                argb_color = CoTProtocolHandler.hex_to_argb_int(hex_color)
                if not team_name:
                    team_name = CoTProtocolHandler.hex_color_to_team(hex_color)

            # For GPS position markers the user's TAK callsign (stored in
            # marker["callsign"]) takes priority over the generic name/label so
            # that WinTAK displays the tactical identifier of the person rather
            # than their login username.  For all other marker types the
            # display name (marker["name"]) retains priority as before.
            if lpu5_type == "gps_position":
                callsign_val = marker.get("callsign") or marker.get("name")
            else:
                callsign_val = marker.get("name") or marker.get("callsign")

            return CoTEvent(
                uid=uid,
                cot_type=cot_type,
                lat=lat,
                lon=lon,
                callsign=callsign_val,
                remarks=marker.get("description") or marker.get("remarks"),
                team_name=team_name,
                team_role=marker.get("role"),
                how=how,
                color=argb_color,
                contact_endpoint=marker.get("contact_endpoint") or None,
                is_meshtastic_node=lpu5_type in _MESHTASTIC_LPU5_TYPES,
            )
        except Exception as e:
            logger.error(f"Failed to convert marker to CoT: {e}")
            return None

    @staticmethod
    def marker_to_cot_tombstone(marker: Dict[str, Any]) -> Optional[CoTEvent]:
        """
        Create a CoT tombstone (deletion) event for a map marker.

        TAK clients remove an entity from their map when they receive a CoT
        event whose ``stale`` timestamp is equal to (or earlier than) the
        event's ``time`` timestamp.  This method produces such an event so
        that deleting a marker in LPU5 propagates the deletion to ATAK/WinTAK.

        Args:
            marker: Map marker dictionary (must contain at least ``id``, ``lat``,
                    and ``lng`` / ``lon`` keys).

        Returns:
            CoTEvent configured as a tombstone, or None if conversion fails.
        """
        try:
            cot_event = CoTProtocolHandler.marker_to_cot(marker)
            if cot_event is None:
                return None
            # Make the event immediately stale so TAK clients remove the entity.
            now = datetime.now(timezone.utc)
            cot_event.time = now
            cot_event.start = now
            cot_event.stale = now
            return cot_event
        except Exception as e:
            logger.error("Failed to build CoT tombstone for marker %s: %s", marker.get("id"), e)
            return None

    @staticmethod
    def cot_to_marker(cot_event: CoTEvent) -> Dict[str, Any]:
        """
        Convert a CoT event to map marker

        Args:
            cot_event: CoTEvent object

        Returns:
            Map marker dictionary
        """
        # Map the TAK CoT type back to the LPU5 internal symbol type so the
        # correct icon is rendered in admin_map / overview.
        lpu5_type = CoTProtocolHandler.cot_type_to_lpu5(cot_event.cot_type)

        # For spot-map markers (b-m-p-s-m) the CoT type is the same for all
        # LPU5 shapes.  When the callsign matches a known LPU5 shape name use
        # it directly so that ATAK-placed markers labelled "neutral" or "unknown"
        # are rendered with the correct icon in the LPU5 web UI.
        if cot_event.cot_type == "b-m-p-s-m" and cot_event.callsign:
            callsign_lower = cot_event.callsign.lower()
            if callsign_lower in CoTProtocolHandler.LPU5_TO_COT_TYPE:
                lpu5_type = callsign_lower

        # Refine the type for ATAK-specific CoT sources so they render with
        # the correct icon rather than the generic blue-rectangle ("friendly"):
        #   • Meshtastic SA beacons forwarded by an ATAK Meshtastic plugin carry a
        #     <meshtastic> element in their <detail> block.  These are checked first
        #     because ATAK Meshtastic SA beacons use how="h-g-*" just like regular
        #     ATAK GPS SA beacons; the <meshtastic> element is the authoritative
        #     signal that this is a Meshtastic node, not a human ATAK user.
        #   • Friendly CoT events without a <meshtastic> element → tak_maker
        #     (covers all TAK clients: ATAK h-g GPS SA, ATAK h-e human-entry,
        #     iTAK m-g machine-generated, WinTAK h-t, etc.).
        #     LPU5's own GPS positions are created directly via /api/map/symbols
        #     and never pass through CoT type detection.
        if cot_event.has_meshtastic_detail or lpu5_type == "meshtastic_node":
            lpu5_type = "meshtastic_node"
        elif lpu5_type == "friendly":
            lpu5_type = "tak_maker"
        else:
            # All CoT events originate from ATAK/WinTAK. Remap the four basic
            # shape types to their CBT variants so ATAK-sourced markers are
            # visually distinguished from natively created LPU5 markers.
            lpu5_type = CoTProtocolHandler.ATAK_TO_CBT_TYPE.get(lpu5_type, lpu5_type)

        # CoT events with a "mesh-" UID prefix are LPU5 Meshtastic node forwards
        # imported back via ATAK/WinTAK SA/COT import.  Always map them to type
        # "meshtastic_node" so they render with the Meshtastic blue-circle icon
        # instead of a generic ground marker.
        if cot_event.uid.startswith("mesh-"):
            lpu5_type = "meshtastic_node"

        # Derive the shortName for meshtastic_node markers (max 4 characters).
        # Priority: <meshtastic shortName> from XML > callsign[:4].
        _MESH_TYPES = ("meshtastic_node", "node", "gateway", "gps_position")
        short_name: Optional[str] = None
        if lpu5_type in _MESH_TYPES:
            raw = cot_event.meshtastic_short_name or (cot_event.callsign[:4] if cot_event.callsign else None)
            short_name = raw[:4] if raw else None

        return {
            "id": cot_event.uid,
            "name": cot_event.callsign,
            "callsign": cot_event.callsign,
            "lat": cot_event.lat,
            "lng": cot_event.lon,
            "altitude": cot_event.hae,
            "type": lpu5_type,
            "status": lpu5_type,
            "description": cot_event.remarks,
            "team": cot_event.team_name,
            "role": cot_event.team_role,
            "timestamp": cot_event._format_time(cot_event.time),
            "cot_type": cot_event.cot_type,
            "source": "cot",
            "how": cot_event.how,
            "shortName": short_name,
            "symbolLink": CoTProtocolHandler.get_symbol_link(lpu5_type),
        }
    
    @staticmethod
    def validate_cot_xml(xml_string: str) -> bool:
        """
        Validate CoT XML structure
        
        Args:
            xml_string: XML string to validate
            
        Returns:
            True if valid CoT XML, False otherwise
        """
        try:
            root = ET.fromstring(xml_string)
            if root.tag != "event":
                return False
            
            # Check required attributes
            if not all(root.get(attr) for attr in ["version", "uid", "type"]):
                return False
            
            # Check for point element
            point = root.find("point")
            if point is None:
                return False
            
            # Validate coordinates
            lat = float(point.get("lat", "invalid"))
            lon = float(point.get("lon", "invalid"))
            
            if not (-90 <= lat <= 90) or not (-180 <= lon <= 180):
                return False
            
            return True
        except Exception:
            return False
